create table bz_item_bucket_rollup (
    bucket_start_epoch_millis bigint not null,
    bucket_end_epoch_millis bigint not null,
    bucket_granularity varchar(16) not null,
    product_id varchar(255) not null,
    sample_count integer not null,
    valid_sample_count integer not null,
    anomaly_sample_count integer not null default 0,
    partial boolean not null default false,
    representative_snapshot_ts bigint,
    median_buy_price double precision,
    median_sell_price double precision,
    median_mid_price double precision,
    median_spread double precision,
    p10_mid_price double precision,
    p25_mid_price double precision,
    p75_mid_price double precision,
    p90_mid_price double precision,
    min_mid_price double precision,
    max_mid_price double precision,
    winsorized_avg_mid_price double precision,
    median_buy_volume double precision,
    median_sell_volume double precision,
    min_liquidity double precision,
    max_liquidity double precision,
    first_snapshot_ts bigint,
    last_snapshot_ts bigint,
    created_at_epoch_millis bigint not null,
    updated_at_epoch_millis bigint not null,
    primary key (bucket_start_epoch_millis, bucket_granularity, product_id)
);

create index idx_bz_item_bucket_rollup_product_bucket
    on bz_item_bucket_rollup (product_id, bucket_granularity, bucket_start_epoch_millis desc);

create table bz_item_anomaly_segment (
    id bigint generated by default as identity primary key,
    bucket_start_epoch_millis bigint not null,
    bucket_end_epoch_millis bigint not null,
    bucket_granularity varchar(16) not null,
    product_id varchar(255) not null,
    segment_start_epoch_millis bigint not null,
    segment_end_epoch_millis bigint not null,
    representative_snapshot_ts bigint,
    peak_snapshot_ts bigint,
    sample_count integer not null,
    anomaly_score double precision not null,
    reason_code varchar(64) not null,
    fragmented boolean not null default false,
    median_buy_price double precision,
    median_sell_price double precision,
    median_mid_price double precision,
    median_spread double precision,
    median_buy_volume double precision,
    median_sell_volume double precision,
    created_at_epoch_millis bigint not null,
    updated_at_epoch_millis bigint not null
);

create index idx_bz_item_anomaly_segment_product_bucket
    on bz_item_anomaly_segment (product_id, bucket_granularity, segment_start_epoch_millis desc);

create table ah_item_bucket_rollup (
    bucket_start_epoch_millis bigint not null,
    bucket_end_epoch_millis bigint not null,
    bucket_granularity varchar(16) not null,
    item_key varchar(255) not null,
    sample_count integer not null,
    valid_sample_count integer not null,
    anomaly_sample_count integer not null default 0,
    partial boolean not null default false,
    representative_snapshot_ts bigint,
    median_bin_lowest5_mean double precision,
    median_bin_p50 double precision,
    median_bin_p95 double precision,
    median_bid_p50 double precision,
    median_bin_count double precision,
    median_ending_soon_count double precision,
    p10_bin_p50 double precision,
    p25_bin_p50 double precision,
    p75_bin_p50 double precision,
    p90_bin_p50 double precision,
    min_bin_p50 double precision,
    max_bin_p50 double precision,
    winsorized_avg_bin_p50 double precision,
    first_snapshot_ts bigint,
    last_snapshot_ts bigint,
    created_at_epoch_millis bigint not null,
    updated_at_epoch_millis bigint not null,
    primary key (bucket_start_epoch_millis, bucket_granularity, item_key)
);

create index idx_ah_item_bucket_rollup_item_bucket
    on ah_item_bucket_rollup (item_key, bucket_granularity, bucket_start_epoch_millis desc);

create table ah_item_anomaly_segment (
    id bigint generated by default as identity primary key,
    bucket_start_epoch_millis bigint not null,
    bucket_end_epoch_millis bigint not null,
    bucket_granularity varchar(16) not null,
    item_key varchar(255) not null,
    segment_start_epoch_millis bigint not null,
    segment_end_epoch_millis bigint not null,
    representative_snapshot_ts bigint,
    peak_snapshot_ts bigint,
    sample_count integer not null,
    anomaly_score double precision not null,
    reason_code varchar(64) not null,
    fragmented boolean not null default false,
    median_bin_lowest5_mean double precision,
    median_bin_p50 double precision,
    median_bin_p95 double precision,
    median_bid_p50 double precision,
    median_bin_count double precision,
    median_ending_soon_count double precision,
    created_at_epoch_millis bigint not null,
    updated_at_epoch_millis bigint not null
);

create index idx_ah_item_anomaly_segment_item_bucket
    on ah_item_anomaly_segment (item_key, bucket_granularity, segment_start_epoch_millis desc);

create table item_bucket_materialization_state (
    bucket_start_epoch_millis bigint not null,
    bucket_end_epoch_millis bigint not null,
    bucket_granularity varchar(16) not null,
    market_type varchar(8) not null,
    source_partition varchar(255) not null,
    finalized boolean not null default false,
    failed boolean not null default false,
    raw_row_count bigint not null default 0,
    rollup_row_count bigint not null default 0,
    anomaly_row_count bigint not null default 0,
    finalized_at_epoch_millis bigint,
    updated_at_epoch_millis bigint not null,
    primary key (bucket_start_epoch_millis, bucket_granularity, market_type)
);

create index idx_item_bucket_materialization_state_partition
    on item_bucket_materialization_state (source_partition, market_type);

create index idx_item_bucket_materialization_state_unfinalized
    on item_bucket_materialization_state (finalized, failed, market_type, bucket_granularity, bucket_start_epoch_millis desc);
