create table flip_definition (
    flip_key varchar(128) not null,
    stable_flip_id uuid not null unique,
    flip_type varchar(255) not null check ((flip_type in ('AUCTION','BAZAAR','CRAFTING','FORGE','KATGRADE','FUSION'))),
    result_item_id varchar(255) not null,
    steps_json text not null,
    constraints_json text not null,
    key_version integer not null,
    created_at_epoch_millis bigint not null,
    updated_at_epoch_millis bigint not null,
    primary key (flip_key)
);

create table flip_current (
    flip_key varchar(128) not null,
    stable_flip_id uuid not null unique,
    flip_type varchar(255) not null check ((flip_type in ('AUCTION','BAZAAR','CRAFTING','FORGE','KATGRADE','FUSION'))),
    snapshot_timestamp_epoch_millis bigint not null,
    required_capital bigint,
    expected_profit bigint,
    roi float(53),
    roi_per_hour float(53),
    duration_seconds bigint,
    fees bigint,
    liquidity_score float(53),
    risk_score float(53),
    partial boolean not null,
    partial_reasons_json text not null,
    updated_at_epoch_millis bigint not null,
    primary key (flip_key)
);

create index idx_flip_definition_flip_type
    on flip_definition (flip_type);

create table flip_trend_segment (
    id bigint generated by default as identity,
    flip_key varchar(128) not null,
    valid_from_snapshot_epoch_millis bigint not null,
    valid_to_snapshot_epoch_millis bigint not null,
    required_capital bigint,
    expected_profit bigint,
    roi float(53),
    roi_per_hour float(53),
    duration_seconds bigint,
    fees bigint,
    liquidity_score float(53),
    risk_score float(53),
    partial boolean not null,
    sample_count integer not null,
    created_at_epoch_millis bigint not null,
    updated_at_epoch_millis bigint not null,
    primary key (id)
);

create index idx_flip_current_snapshot_ts_epoch_millis
    on flip_current (snapshot_timestamp_epoch_millis);

create index idx_flip_current_flip_type
    on flip_current (flip_type);

create index idx_flip_current_expected_profit
    on flip_current (expected_profit);

create index idx_flip_current_roi
    on flip_current (roi);

create index idx_flip_current_roi_per_hour
    on flip_current (roi_per_hour);

create index idx_flip_current_liquidity_score
    on flip_current (liquidity_score);

create index idx_flip_current_risk_score
    on flip_current (risk_score);

create index idx_flip_trend_segment_flip_key_from_snapshot
    on flip_trend_segment (flip_key, valid_from_snapshot_epoch_millis);

create index idx_flip_trend_segment_validity_window
    on flip_trend_segment (valid_from_snapshot_epoch_millis, valid_to_snapshot_epoch_millis);

alter table flip_current
    add constraint fk_flip_current_definition
    foreign key (flip_key)
    references flip_definition;

alter table flip_trend_segment
    add constraint fk_flip_trend_definition
    foreign key (flip_key)
    references flip_definition;
